# Offline RAG Knowledge Base Audit

In [1]:
from pathlib import Path
import pandas as pd
import sqlite3
import json

current = Path.cwd().resolve()

PROJECT_ROOT = None

for candidate in [current, *current.parents]:
    if (
        (candidate / "research").is_dir()
        and (candidate / "pubspec.yaml").is_file()
    ):
        PROJECT_ROOT = candidate
        break

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        f"Could not locate project root from: {current}"
    )

RESEARCH_DIR = PROJECT_ROOT / "research"

RAG_DIR = RESEARCH_DIR / "rag"

SOURCE_DIR = (
    RAG_DIR / "source_documents"
)

PROCESSED_DIR = (
    RAG_DIR / "processed"
)

DATABASE_DIR = (
    RAG_DIR / "database"
)

EVALUATION_DIR = (
    RAG_DIR / "evaluation"
)

for directory in [
    SOURCE_DIR,
    PROCESSED_DIR,
    DATABASE_DIR,
    EVALUATION_DIR
]:
    directory.mkdir(
        parents=True,
        exist_ok=True
    )

print("OFFLINE RAG ENVIRONMENT")
print("=" * 60)

print("Project root:", PROJECT_ROOT)
print("RAG directory:", RAG_DIR)
print("Source directory:", SOURCE_DIR)
print("Database directory:", DATABASE_DIR)

OFFLINE RAG ENVIRONMENT
============================================================
Project root: /Users/mirshad/Desktop/Decentralized-Hiking-AI
RAG directory: /Users/mirshad/Desktop/Decentralized-Hiking-AI/research/rag
Source directory: /Users/mirshad/Desktop/Decentralized-Hiking-AI/research/rag/source_documents
Database directory: /Users/mirshad/Desktop/Decentralized-Hiking-AI/research/rag/database

In [2]:
RAG_CATEGORIES = [
    "general_first_aid",
    "hypothermia",
    "heat_illness",
    "heavy_rain",
    "strong_wind",
    "water_safety",
    "remote_emergency"
]

print("OFFLINE KNOWLEDGE CATEGORIES")
print("=" * 60)

for index, category in enumerate(
    RAG_CATEGORIES,
    start=1
):
    print(
        f"{index}. {category}"
    )

print()
print(
    "Total categories:",
    len(RAG_CATEGORIES)
)

OFFLINE KNOWLEDGE CATEGORIES
============================================================
1. general_first_aid
2. hypothermia
3. heat_illness
4. heavy_rain
5. strong_wind
6. water_safety
7. remote_emergency

Total categories: 7

In [3]:
CATALOG_FILE = (
    RAG_DIR / "source_catalog.csv"
)

print("SOURCE CATALOG")
print("=" * 60)

print(
    "Catalog exists:",
    CATALOG_FILE.exists()
)

if not CATALOG_FILE.exists():
    raise FileNotFoundError(
        f"Missing source catalog: {CATALOG_FILE}"
    )

catalog = pd.read_csv(
    CATALOG_FILE
)

print(
    "Catalog shape:",
    catalog.shape
)

print(
    "Columns:"
)

for column in catalog.columns:
    print(" -", column)

display(
    catalog.head()
)

SOURCE CATALOG
============================================================
Catalog exists: True
Catalog shape: (17, 15)
Columns:
 - source_id
 - title
 - organization
 - categories
 - source_url
 - official_domain
 - publication_date
 - retrieved_date
 - language
 - file_type
 - local_path
 - download_status
 - authoritative
 - primary_source
 - notes

,source_id,title,organization,categories,source_url,official_domain,publication_date,retrieved_date,language,file_type,local_path,download_status,authoritative,primary_source,notes
0,SRC_001,"IFRC International First Aid, Resuscitation an...",IFRC,general_first_aid;hypothermia;heat_illness;wat...,https://www.ifrc.org/sites/default/files/2026-...,www.ifrc.org,2026-03-18,2026-10-18,en,pdf,source_documents/general_first_aid/ifrc_first_...,downloaded,True,True,2025 edition; official IFRC listing dates rele...
1,SRC_002,Preventing Hypothermia,Centers for Disease Control and Prevention (CDC),hypothermia,https://www.cdc.gov/winter-weather/prevention/...,www.cdc.gov,2024-05-15,2026-10-18,en,html,NaN,url_only,True,True,US context; preserve distinctions between hypo...
2,SRC_003,Heat-related Illnesses,Centers for Disease Control and Prevention (CD...,heat_illness,https://www.cdc.gov/niosh/heat-stress/about/il...,www.cdc.gov,NaN,2026-10-18,en,html,NaN,url_only,True,True,Worker-oriented guidance; exertional exposure ...
3,SRC_004,"About Water Treatment Options When Hiking, Cam...",Centers for Disease Control and Prevention (CDC),water_safety,https://www.cdc.gov/drinking-water/prevention/...,www.cdc.gov,NaN,2026-10-18,en,html,NaN,url_only,True,True,Product instructions and contaminant-specific ...
4,SRC_005,During a Flood,NOAA National Weather Service (NWS),heavy_rain;water_safety,https://www.weather.gov/safety/flood-during,www.weather.gov,2018-03-12,2026-10-18,en,html,source_documents/heavy_rain/nws_during_a_flood...,downloaded,True,True,US emergency numbers and warning systems are n...

In [4]:
REQUIRED_CATALOG_COLUMNS = [
    "source_id",
    "title",
    "organization",
    "categories",
    "source_url",
    "official_domain",
    "publication_date",
    "retrieved_date",
    "language",
    "file_type",
    "local_path",
    "download_status",
    "authoritative",
    "primary_source",
    "notes"
]

missing_columns = [
    column
    for column in REQUIRED_CATALOG_COLUMNS
    if column not in catalog.columns
]

print("CATALOG SCHEMA VALIDATION")
print("=" * 60)

print(
    "Missing required columns:",
    missing_columns
)

print(
    "Duplicate source IDs:",
    catalog["source_id"]
    .duplicated()
    .sum()
)

critical_columns = [
    "source_id",
    "title",
    "organization",
    "categories",
    "source_url"
]

print("\nMissing critical metadata:")

print(
    catalog[
        critical_columns
    ]
    .isna()
    .sum()
)

print(
    "\nSchema valid:",
    len(missing_columns) == 0
)

CATALOG SCHEMA VALIDATION
============================================================
Missing required columns: []
Duplicate source IDs: 0

Missing critical metadata:
source_id       0
title           0
organization    0
categories      0
source_url      0
dtype: int64

Schema valid: True

In [5]:
print("DOWNLOAD STATUS")
print("=" * 60)

print(
    catalog["download_status"]
    .value_counts(
        dropna=False
    )
)

print()
print(
    "Total catalog sources:",
    len(catalog)
)

DOWNLOAD STATUS
============================================================
download_status
downloaded    11
url_only       6
Name: count, dtype: int64

Total catalog sources: 17

In [6]:
def resolve_local_path(local_path):

    if pd.isna(local_path):
        return None

    value = str(
        local_path
    ).strip()

    if not value:
        return None

    path = Path(value)

    if path.is_absolute():
        return path

    # Catalog paths are expected to be relative
    # to research/rag/
    return RAG_DIR / path


catalog[
    "resolved_local_path"
] = catalog[
    "local_path"
].apply(
    resolve_local_path
)

catalog[
    "local_file_exists"
] = catalog[
    "resolved_local_path"
].apply(
    lambda path:
        path is not None
        and path.is_file()
)

catalog[
    "local_file_size_bytes"
] = catalog[
    "resolved_local_path"
].apply(
    lambda path:
        path.stat().st_size
        if (
            path is not None
            and path.is_file()
        )
        else 0
)

print("LOCAL FILE VALIDATION")
print("=" * 60)

print(
    "Catalog sources:",
    len(catalog)
)

print(
    "Local files found:",
    int(
        catalog[
            "local_file_exists"
        ].sum()
    )
)

print(
    "Missing local files:",
    int(
        (
            ~catalog[
                "local_file_exists"
            ]
        ).sum()
    )
)

print(
    "Zero-byte local files:",
    int(
        (
            catalog[
                "local_file_exists"
            ]
            &
            (
                catalog[
                    "local_file_size_bytes"
                ] == 0
            )
        ).sum()
    )
)

LOCAL FILE VALIDATION
============================================================
Catalog sources: 17
Local files found: 11
Missing local files: 6
Zero-byte local files: 0

In [7]:
offline_catalog = (
    catalog[
        catalog[
            "local_file_exists"
        ]
        &
        (
            catalog[
                "local_file_size_bytes"
            ] > 0
        )
    ]
    .copy()
    .reset_index(
        drop=True
    )
)

print("OFFLINE-ELIGIBLE KNOWLEDGE SOURCES")
print("=" * 60)

print(
    "Offline sources:",
    len(offline_catalog)
)

print(
    "Excluded URL-only/missing sources:",
    len(catalog)
    - len(offline_catalog)
)

display(
    offline_catalog[
        [
            "source_id",
            "title",
            "organization",
            "categories",
            "file_type",
            "local_file_size_bytes"
        ]
    ]
)

OFFLINE-ELIGIBLE KNOWLEDGE SOURCES
============================================================
Offline sources: 11
Excluded URL-only/missing sources: 6

,source_id,title,organization,categories,file_type,local_file_size_bytes
0,SRC_001,"IFRC International First Aid, Resuscitation an...",IFRC,general_first_aid;hypothermia;heat_illness;wat...,pdf,6261070
1,SRC_005,During a Flood,NOAA National Weather Service (NWS),heavy_rain;water_safety,html,26657
2,SRC_006,Lightning Safety,NOAA National Weather Service (NWS),heavy_rain,html,26044
3,SRC_007,During a High Wind Event,NOAA National Weather Service (NWS),strong_wind,html,27157
4,SRC_008,Before a High Wind Event,NOAA National Weather Service (NWS),strong_wind,html,26047
5,SRC_009,Outdoor Emergency Plan,US National Park Service (NPS),remote_emergency,html,76363
6,SRC_010,Ten Essentials,US National Park Service (NPS),remote_emergency,html,49027
7,SRC_014,Hypothermia,NHS (England),hypothermia,html,32978
8,SRC_015,Heat exhaustion and heatstroke,NHS (England),heat_illness,html,33587
9,SRC_016,Cuts and grazes,NHS (England),general_first_aid,html,33991
10,SRC_017,Emergency Disinfection of Drinking Water,US Environmental Protection Agency (EPA),water_safety,html,64819

In [8]:
def extract_categories(value):

    if pd.isna(value):
        return []

    text = str(value)

    for separator in [
        "|",
        ";",
        ","
    ]:
        text = text.replace(
            separator,
            "|"
        )

    return [
        item.strip()
        for item in text.split("|")
        if item.strip()
    ]


category_counts = {
    category: 0
    for category in RAG_CATEGORIES
}

unknown_categories = set()

for value in offline_catalog[
    "categories"
]:

    for category in extract_categories(
        value
    ):

        if category in category_counts:

            category_counts[
                category
            ] += 1

        else:

            unknown_categories.add(
                category
            )


category_coverage = pd.DataFrame({
    "category":
        list(
            category_counts.keys()
        ),

    "offline_source_count":
        list(
            category_counts.values()
        )
})

category_coverage[
    "has_offline_coverage"
] = (
    category_coverage[
        "offline_source_count"
    ] > 0
)

print("OFFLINE CATEGORY COVERAGE")
print("=" * 60)

display(
    category_coverage
)

print(
    "Unknown category values:",
    sorted(
        unknown_categories
    )
)

print(
    "All required categories covered:",
    bool(
        category_coverage[
            "has_offline_coverage"
        ].all()
    )
)

OFFLINE CATEGORY COVERAGE
============================================================

            category  offline_source_count  has_offline_coverage
0  general_first_aid                     2                  True
1        hypothermia                     2                  True
2       heat_illness                     2                  True
3         heavy_rain                     2                  True
4        strong_wind                     2                  True
5       water_safety                     3                  True
6   remote_emergency                     3                  True

Unknown category values: []
All required categories covered: True

## Offline Knowledge Text Extraction

In [9]:
import importlib.util

required_packages = {
    "BeautifulSoup": "bs4",
    "PyPDF": "pypdf"
}

print("TEXT EXTRACTION DEPENDENCIES")
print("=" * 60)

dependency_status = {}

for name, module in required_packages.items():

    installed = (
        importlib.util.find_spec(
            module
        ) is not None
    )

    dependency_status[name] = installed

    print(
        f"{name}: {installed}"
    )

TEXT EXTRACTION DEPENDENCIES
============================================================
BeautifulSoup: True
PyPDF: True

In [10]:
from bs4 import BeautifulSoup
import re


def clean_whitespace(text):

    text = text.replace(
        "\xa0",
        " "
    )

    text = re.sub(
        r"[ \t]+",
        " ",
        text
    )

    text = re.sub(
        r"\n[ \t]+",
        "\n",
        text
    )

    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text
    )

    return text.strip()


def extract_html_text(path):

    html = path.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    soup = BeautifulSoup(
        html,
        "html.parser"
    )

    # Remove elements that normally contain
    # non-knowledge webpage content.
    for element in soup(
        [
            "script",
            "style",
            "noscript",
            "svg",
            "form"
        ]
    ):
        element.decompose()

    # Prefer the semantic main/article content
    # when the webpage provides it.
    content = (
        soup.find("main")
        or soup.find("article")
        or soup.body
        or soup
    )

    text = content.get_text(
        separator="\n",
        strip=True
    )

    return clean_whitespace(
        text
    )

In [11]:
from pypdf import PdfReader


def extract_pdf_text(path):

    reader = PdfReader(
        str(path)
    )

    page_texts = []

    for page_number, page in enumerate(
        reader.pages,
        start=1
    ):

        text = (
            page.extract_text()
            or ""
        )

        text = clean_whitespace(
            text
        )

        if text:
            page_texts.append(
                text
            )

    combined_text = "\n\n".join(
        page_texts
    )

    return (
        clean_whitespace(
            combined_text
        ),
        len(reader.pages)
    )

In [12]:
extraction_records = []

for _, row in offline_catalog.iterrows():

    path = row[
        "resolved_local_path"
    ]

    file_type = str(
        row["file_type"]
    ).lower().strip()

    status = "success"
    error = None
    page_count = None
    text = ""

    try:

        if file_type == "pdf":

            text, page_count = (
                extract_pdf_text(
                    path
                )
            )

        elif file_type in [
            "html",
            "htm"
        ]:

            text = extract_html_text(
                path
            )

        else:

            status = (
                "unsupported_file_type"
            )

    except Exception as exc:

        status = "error"
        error = str(exc)

    extraction_records.append({
        "source_id":
            row["source_id"],

        "title":
            row["title"],

        "organization":
            row["organization"],

        "categories":
            row["categories"],

        "file_type":
            file_type,

        "page_count":
            page_count,

        "extraction_status":
            status,

        "character_count":
            len(text),

        "word_count":
            len(text.split()),

        "error":
            error,

        "extracted_text":
            text
    })


extracted_documents = pd.DataFrame(
    extraction_records
)

print("TEXT EXTRACTION")
print("=" * 60)

display(
    extracted_documents[
        [
            "source_id",
            "title",
            "file_type",
            "page_count",
            "extraction_status",
            "character_count",
            "word_count",
            "error"
        ]
    ]
)

TEXT EXTRACTION
============================================================

,source_id,title,file_type,page_count,extraction_status,character_count,word_count,error
0,SRC_001,"IFRC International First Aid, Resuscitation an...",pdf,594.0,success,1527421,227058,None
1,SRC_005,During a Flood,html,NaN,success,2638,410,None
2,SRC_006,Lightning Safety,html,NaN,success,1876,267,None
3,SRC_007,During a High Wind Event,html,NaN,success,2930,484,None
4,SRC_008,Before a High Wind Event,html,NaN,success,2022,314,None
5,SRC_009,Outdoor Emergency Plan,html,NaN,success,10199,1845,None
6,SRC_010,Ten Essentials,html,NaN,success,6230,1043,None
7,SRC_014,Hypothermia,html,NaN,success,2338,425,None
8,SRC_015,Heat exhaustion and heatstroke,html,NaN,success,3823,663,None
9,SRC_016,Cuts and grazes,html,NaN,success,4280,839,None
10,SRC_017,Emergency Disinfection of Drinking Water,html,NaN,success,6621,1117,None

In [13]:
print("EXTRACTION VALIDATION")
print("=" * 60)

print(
    "Documents attempted:",
    len(extracted_documents)
)

print(
    "Successful:",
    (
        extracted_documents[
            "extraction_status"
        ] == "success"
    ).sum()
)

print(
    "Failed:",
    (
        extracted_documents[
            "extraction_status"
        ] != "success"
    ).sum()
)

print(
    "Empty documents:",
    (
        extracted_documents[
            "character_count"
        ] == 0
    ).sum()
)

print(
    "Documents under 100 words:",
    (
        extracted_documents[
            "word_count"
        ] < 100
    ).sum()
)

print(
    "Total extracted words:",
    extracted_documents[
        "word_count"
    ].sum()
)

EXTRACTION VALIDATION
============================================================
Documents attempted: 11
Successful: 11
Failed: 0
Empty documents: 0
Documents under 100 words: 0
Total extracted words: 234465

In [14]:
for _, row in extracted_documents.iterrows():

    print("\n")
    print("=" * 80)

    print(
        row["source_id"],
        "-",
        row["title"]
    )

    print(
        "Organization:",
        row["organization"]
    )

    print(
        "Words:",
        row["word_count"]
    )

    print("-" * 80)

    preview = row[
        "extracted_text"
    ][:1500]

    print(preview)

    print("\n[PREVIEW END]")

================================================================================
SRC_001 - IFRC International First Aid, Resuscitation and Education Guidelines 2025
Organization: IFRC
Words: 227058
--------------------------------------------------------------------------------
INTERNATIONAL FIRST AID,
RESUSCITATION AND EDUCATION
GUIDELINES 2025

Contents
TOPIC INDEX 4
INTRODUCTION 11
CONTEXTUALIZING FIRST AID AND FIRST AID EDUCATION 27
FIRST AID EDUCATION 71
FIRST AID 111
GENERAL APPROACH 113
RESUSCITATION 151
BREATHING PROBLEMS 231
TRAUMA 255
MEDICAL CONDITIONS 357
ENVIRONMENTAL 445
MENTAL DISTRESS 485
GLOSSARY AND REFERENCES 523

Audience: First aid programme designers, programme managers, education and scienti ﬁc
committees, trainers

Red Cross Red Crescent Networks
Coordinated by IFRC Global First Aid Reference Centre

© International Federation of Red Cross and Red Crescent Societies, Geneva, 2025
Copies of all or part of this study may be made for non-commercial use, providing the source is
acknowledged. The IFRC would appreciate receiving details of its use. Requests for commercial
reproduction should be directed to the IFRC at secretariat@ifrc.org.

The opinions and recommendations expressed in this study do not necessarily represent the
ofﬁcial policy of the IFRC or of individual National Red Cross or Red Crescent Societies. All photos
used in this study are copyright of the IFRC unless otherwise indicated.

Chemin des Crêts 17, Petit-Saconnex, 1209 Geneva, Switzerland
Postal address: P.O. Box 303, 1211 Geneva 19, Switzerland
T +41 (0)22 730 42 22 | secretariat@ifrc.org | ifrc.org

International ﬁrst aid, resuscitation and education guidelines 2025
globalﬁrstaidcentre.org

2 | International ﬁrst aid, resusci

[PREVIEW END]


================================================================================
SRC_005 - During a Flood
Organization: NOAA National Weather Service (NWS)
Words: 410
--------------------------------------------------------------------------------
HOME
FORECAST
Local
Graphical
Aviation
Marine
Rivers and Lakes
Hurricanes
Severe Weather
Fire Weather
Sunrise/Sunset
Long Range Forecasts
Climate Prediction
Space Weather
PAST WEATHER
Past Weather
Astronomical Data
Certified Weather Data
SAFETY
INFORMATION
Wireless Emergency Alerts
Weather-Ready Nation
Brochures
Cooperative Observers
Daily Briefing
Damage/Fatality/Injury Statistics
Forecast Models
GIS Data Portal
NOAA Weather Radio
Publications
SKYWARN Storm Spotters
StormReady
TsunamiReady
Service Change Notices
EDUCATION
NEWS
SEARCH
ABOUT
About NWS
Organization
For NWS Employees
National Centers
Careers
Contact Us
Glossary
Social Media
NWS Transformation
Safety
National Program
During a Flood
Weather.gov
>
Safety
> During a Flood
Flooding Resources
During a flood, water levels and the rate the water is flowing can quickly change. Remain aware and monitor local radio and television outlets. Avoid flood waters at all costs and evacuate immediately when water starts to rise. Don't wait until it's too late!
Stay Informed:
Listen to radio and television, including NOAA Weather Radio if possible, check the Internet and social media for information and updates.
Get to Higher Ground:
If you live in a flood prone area or are camping in a low lying area, get to higher ground immediately.
Obey Evacuation Orders:
If told to evacuate, do so immediately. Lock your home when you leave. If you have time, disconnect utilities and appliances.
Practice Electrical Safety:
Don't go into a basem

[PREVIEW END]


================================================================================
SRC_006 - Lightning Safety
Organization: NOAA National Weather Service (NWS)
Words: 267
--------------------------------------------------------------------------------
HOME
FORECAST
Local
Graphical
Aviation
Marine
Rivers and Lakes
Hurricanes
Severe Weather
Fire Weather
Sunrise/Sunset
Long Range Forecasts
Climate Prediction
Space Weather
PAST WEATHER
Past Weather
Astronomical Data
Certified Weather Data
SAFETY
INFORMATION
Wireless Emergency Alerts
Weather-Ready Nation
Brochures
Cooperative Observers
Daily Briefing
Damage/Fatality/Injury Statistics
Forecast Models
GIS Data Portal
NOAA Weather Radio
Publications
SKYWARN Storm Spotters
StormReady
TsunamiReady
Service Change Notices
EDUCATION
NEWS
SEARCH
ABOUT
About NWS
Organization
For NWS Employees
National Centers
Careers
Contact Us
Glossary
Social Media
NWS Transformation
Safety
National Program
Lightning Safety
Weather.gov
>
Safety
> Lightning Safety
Lightning Resources
There is no safe place outside when thunderstorms are in the area. If you hear thunder, you are likely within striking distance of the storm. Just remember,
When Thunder Roars, Go Indoors.
Too many people wait far too long to get to a safe place when thunderstorms approach. Unfortunately, these delayed actions lead to many of the lightning deaths and injuries in the United States. Below are tips on how to stay safe indoors and outdoors as well as brochures and other tools to teach lightning safety.
Lightning Safety Outdoors
Lightning Safety Indoors
Dr. Lightning:
Safety
Overview of Lightning Safety
N
OAA Lightning Safety Brochure
What You Need to Know: Tips for Safety
Lightning Safety and Recreational Activities
Lightning Sa

[PREVIEW END]


================================================================================
SRC_007 - During a High Wind Event
Organization: NOAA National Weather Service (NWS)
Words: 484
--------------------------------------------------------------------------------
HOME
FORECAST
Local
Graphical
Aviation
Marine
Rivers and Lakes
Hurricanes
Severe Weather
Fire Weather
Sunrise/Sunset
Long Range Forecasts
Climate Prediction
Space Weather
PAST WEATHER
Past Weather
Astronomical Data
Certified Weather Data
SAFETY
INFORMATION
Wireless Emergency Alerts
Brochures
Weather-Ready Nation
Cooperative Observers
Daily Briefing
Damage/Fatality/Injury Statistics
Forecast Models
GIS Data Portal
NOAA Weather Radio
Publications
SKYWARN Storm Spotters
StormReady
TsunamiReady
Service Change Notices
EDUCATION
NEWS
SEARCH
ABOUT
About NWS
Organization
For NWS Employees
National Centers
Careers
Contact Us
Glossary
Social Media
NWS Transformation
Safety
National Program
During a High Wind Event
Weather.gov
>
Safety
> During a High Wind Event
Wind Resources
Take Shelter
Immediately go inside a sturdy building during a high wind warning or severe thunderstorm warning and move to an interior room or basement.
If you are in a mobile home, move to a sturdy building before the winds pick up or the storm system reaches your location.
Listen to the local news or
NOAA Weather Radio
for updates.
If
Caught Outside or Driving
Take shelter in your car if you are not near a sturdy building. If possible, drive to a nearby sturdy building. Otherwise, move your car to a location where it is less likely to be hit by falling trees or power lines.
If no shelter is available avoid trees, power lines, and the side of the road. Keep in mind that power lines that are laying on the ground m

[PREVIEW END]


================================================================================
SRC_008 - Before a High Wind Event
Organization: NOAA National Weather Service (NWS)
Words: 314
--------------------------------------------------------------------------------
HOME
FORECAST
Local
Graphical
Aviation
Marine
Rivers and Lakes
Hurricanes
Severe Weather
Fire Weather
Sunrise/Sunset
Long Range Forecasts
Climate Prediction
Space Weather
PAST WEATHER
Past Weather
Astronomical Data
Certified Weather Data
SAFETY
INFORMATION
Wireless Emergency Alerts
Weather-Ready Nation
Brochures
Cooperative Observers
Daily Briefing
Damage/Fatality/Injury Statistics
Forecast Models
GIS Data Portal
NOAA Weather Radio
Publications
SKYWARN Storm Spotters
StormReady
TsunamiReady
Service Change Notices
EDUCATION
NEWS
SEARCH
ABOUT
About NWS
Organization
For NWS Employees
National Centers
Careers
Contact Us
Glossary
Social Media
NWS Transformation
Safety
National Program
Before a High Wind Event
Weather.gov
>
Safety
> Before a High Wind Event
Wind Resources
Trim tree branches away from your house and power lines.
Secure loose gutters and shutters.
Identify an interior room of your house, such as a basement or interior bathroom, that you can take shelter in during high wind warnings.
If you live in a mobile home, identify a sturdy building you can go to if NWS issues a high wind or severe thunderstorm warning.
Charge batteries of all essential items such as cell phones and booster packs, weather radios and power tools such as a reciprocating saw, which you might need to clear debris.
Update your emergency kit and be sure to include enough food and water to last for 3 days for each person in your home.
Make a list of items outside your home you will need to tie down or

[PREVIEW END]


================================================================================
SRC_009 - Outdoor Emergency Plan
Organization: US National Park Service (NPS)
Words: 1845
--------------------------------------------------------------------------------
An official website of the United States government
Here's how you know
Here's how you know
Official websites use .gov
A
.gov
website belongs to an official government
organization in the United States.
Secure .gov websites use HTTPS
A
lock
(
) or
https://
means you've safely connected to
the .gov website. Share sensitive information only on official,
secure websites.
Skip to global NPS navigation
Skip to the main content
Skip to the footer section
National Park Service
Search
Open
Menu
Close
Menu
Explore This Park
Explore the National Park Service
Exiting nps.gov
Cancel
Contact Us
Article
Outdoor Emergency Plan
Click the image to download the NPS Outdoor Emergency Plan
Accidents happen. You may become
lost
or
injured
while recreating outdoors. Search and rescue can take hours or days depending on factor such as weather conditions, capacity, and resources whether you are lost or injured. Being prepared for an emergency improves your ability to quickly respond to the situation. It is very important that you practice your plan before you leave so you and anyone joining your adventure knows what to do in case of an emergency. Remember, each trip and activity may have special requirements so you may have to modify your outdoor emergency plan to fit your trip.
Continue reading to learn how you can get the most out of your visit to a park. On this page, you'll also be able to:
Learn what to do
before your trip
Learn about
what to do if you get lost
Learn about
what to do if you get

[PREVIEW END]


================================================================================
SRC_010 - Ten Essentials
Organization: US National Park Service (NPS)
Words: 1043
--------------------------------------------------------------------------------
An official website of the United States government
Here's how you know
Here's how you know
Official websites use .gov
A
.gov
website belongs to an official government
organization in the United States.
Secure .gov websites use HTTPS
A
lock
(
) or
https://
means you've safely connected to
the .gov website. Share sensitive information only on official,
secure websites.
Skip to global NPS navigation
Skip to the main content
Skip to the footer section
National Park Service
Search
Open
Menu
Close
Menu
Explore This Park
Explore the National Park Service
Exiting nps.gov
Cancel
Contact Us
Article
Ten Essentials
Heading out to a national park? Make sure you pack the 10 Essentials!
The 10 Essentials are a collection of important items that can help you or others in the event of minor injuries, sudden weather changes, or unexpected emergencies. The 10 Essentials include basic items you should have with you. You may need additional items depending on the activity in which you participate (i.e., life jacket, bug spray, 2-way satellite messaging device). Visit the specific
park's website
to learn more about the park and make a plan for your activity before you head out. Be sure to tell someone
where you’re going
and when to expect you back.
THE TEN ESSENTIALS
The 10 Essentials are organized into ten categories, or systems
1
:
NAVIGATION
– Map, compass, and GPS system
Navigation items are used when planning your route before your trip, and when orienting yourself in the park during your ac

[PREVIEW END]


================================================================================
SRC_014 - Hypothermia
Organization: NHS (England)
Words: 425
--------------------------------------------------------------------------------
Hypothermia
Hypothermia is a dangerous drop in body temperature below 35C (normal body temperature is around 37C). It's a medical emergency that needs to be treated in hospital.
Symptoms of hypothermia
Symptoms of hypothermia include:
shivering
pale, cold and dry skin – skin and lips may turn blue or grey (on black or brown skin this may be easier to see on the palms of the hands or the soles of the feet)
slurred speech
slow breathing
tiredness or confusion
A baby with hypothermia may be:
cold to touch
floppy
unusually quiet and sleepy and may refuse to feed
Immediate action required:
Go to A&E or call 999 if:
you think you or your child have hypothermia
Find your nearest A&E
Information:
Do not drive to A&E. Ask someone to drive you or call 999 and ask for an ambulance.
Bring any medicines you take with you.
What to do while you're waiting for help for hypothermia
If you think someone has hypothermia, there are things you can do while waiting for medical help.
Do
move the person indoors or somewhere sheltered as quickly as possible
remove any wet clothing, wrap them in a blanket, sleeping bag or dry towel, making sure their head is covered
give them a warm non-alcoholic drink and some sugary food like chocolate if they're fully awake
keep them awake by talking to them until help arrives
make sure you or someone else stays with them
There are things you should not do because they will not help and could make things worse.
Don’t
do not use a hot bath, hot water bottle or heat

[PREVIEW END]


================================================================================
SRC_015 - Heat exhaustion and heatstroke
Organization: NHS (England)
Words: 663
--------------------------------------------------------------------------------
Heat exhaustion and heatstroke
Heat exhaustion does not usually need emergency medical help if you can cool down within 30 minutes. If it turns into heatstroke, it needs to be treated as an emergency.
Symptoms of heat exhaustion and heatstroke
Symptoms of heat exhaustion
The symptoms of heat exhaustion include:
tiredness
dizziness
headache
feeling sick (nausea) or being sick (vomiting)
excessive sweating and skin becoming pale and clammy (a change in skin colour can be harder to see on brown or black skin)
cramps in the arms, legs and stomach
a high temperature
being very thirsty
feeling irritable
The symptoms of heat exhaustion are often the same in adults and children.
If someone is showing signs of heat exhaustion they need to be cooled down and given fluids.
Symptoms of heatstroke
The symptoms of heatstroke include:
a very high temperature
hot skin without sweating
fast breathing and a fast heartbeat
confusion and restlessness
seizure (fit)
loss of consciousness
Heatstroke is a medical emergency. Get immediate medical help if someone has the symptoms of heatstroke.
Things you can do to cool someone down
If someone has heat exhaustion, follow these 4 steps:
Move them to a cool place.
Remove all unnecessary clothing like a jacket or socks.
Give them plenty of water to drink – you can also give them an isotonic sports drink or oral rehydration powder that you mix with water, which will help replace salt lost through sweating.
Cool their skin – spray or sponge them with cool

[PREVIEW END]


================================================================================
SRC_016 - Cuts and grazes
Organization: NHS (England)
Words: 839
--------------------------------------------------------------------------------
Cuts and grazes
Most cuts and grazes can be treated at home and will start to heal in a few days. But some wounds may need to be treated by a medical professional if there's a risk of infection or the cut is serious.
How to treat a cut or graze yourself
You can treat a cut or graze yourself by stopping any bleeding, cleaning the wound, and covering it with a plaster or dressing. This will help stop it getting infected.
If it's painful, you can take painkillers such as
paracetamol
or
ibuprofen
(but do not give
aspirin
to children under 16).
What to do if the wound is bleeding a lot
Wash your hands thoroughly and dry them. Put on disposable gloves if you have some.
Check the wound and make sure there's nothing stuck in it.
If there's nothing in the wound, put pressure on it using a bandage or a clean, folded cloth (such as a tea towel).
If there's something stuck in the wound, do not try to take it out. Make sure not to press down on the object. Press firmly either side of it to push the edges of the wound together.
If the wound is on your hand or arm, raise it above your head. If the wound is on your lower limb, lie down and raise it above the level of your heart. This will help reduce the blood flow.
If blood comes through the bandage or cloth, apply another bandage or cloth on top to put pressure on the wound.
When the bleeding is under control, keep the dressing in place by tying a knot in a bandage over the wound. Support the injured part of your body with a sling or banda

[PREVIEW END]


================================================================================
SRC_017 - Emergency Disinfection of Drinking Water
Organization: US Environmental Protection Agency (EPA)
Words: 1117
--------------------------------------------------------------------------------
Breadcrumb
Home
Ground Water and Drinking Water
Emergency Disinfection of Drinking Water
Información relacionada disponible en español
In an emergency situation where regular water service has been interrupted – like a hurricane, flood, or water pipe breakage – local authorities may recommend using only bottled water, boiled water, or disinfected water until regular water service is restored. The instructions below show you how to boil and disinfect water to kill most disease-causing microorganisms that may be present in the water. However, boiling or disinfection will not destroy other contaminants, such as heavy metals, salts, and most other chemicals.
Print
Emergency Disinfection of Drinking Water
document.
ONLY USE WATER THAT HAS BEEN PROPERLY DISINFECTED FOR DRINKING, COOKING, MAKING ANY PREPARED DRINK, WASHING DISHES AND FOR BRUSHING TEETH.
Use
bottled water
or water you have properly prepared and stored as an emergency water supply.
Boil water
, if you do not have bottled water. Boiling is sufficient to kill pathogenic bacteria, viruses and protozoa (WHO, 2015).
If water is cloudy, let it settle and filter it through a clean cloth, paperboiling water towel, or coffee filter.
Bring water to a rolling boil for at least one minute. At altitudes above 5,000 feet (1,000 meters), boil water for three minutes.
Let water cool naturally and store it in clean containers with covers.
To improve the flat taste of boiled water, add one pinch of salt to each quart or liter of water,

[PREVIEW END]

## Knowledge Cleaning and Chunking Strategy

In [15]:
def clean_extracted_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    # Normalize line endings
    text = text.replace(
        "\r\n",
        "\n"
    ).replace(
        "\r",
        "\n"
    )

    # Remove excessive spaces
    text = re.sub(
        r"[ \t]+",
        " ",
        text
    )

    # Remove spaces around newlines
    text = re.sub(
        r" *\n *",
        "\n",
        text
    )

    # Limit excessive blank lines
    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text
    )

    return text.strip()


extracted_documents[
    "cleaned_text"
] = extracted_documents[
    "extracted_text"
].apply(
    clean_extracted_text
)

extracted_documents[
    "cleaned_word_count"
] = extracted_documents[
    "cleaned_text"
].apply(
    lambda text: len(
        text.split()
    )
)

print("TEXT CLEANING")
print("=" * 60)

display(
    extracted_documents[
        [
            "source_id",
            "word_count",
            "cleaned_word_count"
        ]
    ]
)

TEXT CLEANING
============================================================

   source_id  word_count  cleaned_word_count
0    SRC_001      227058              227058
1    SRC_005         410                 410
2    SRC_006         267                 267
3    SRC_007         484                 484
4    SRC_008         314                 314
5    SRC_009        1845                1845
6    SRC_010        1043                1043
7    SRC_014         425                 425
8    SRC_015         663                 663
9    SRC_016         839                 839
10   SRC_017        1117                1117

In [16]:
NOISE_PATTERNS = [
    "accept cookies",
    "cookie policy",
    "skip to main content",
    "privacy policy",
    "accessibility",
    "javascript",
    "menu",
    "search this site",
    "back to top",
    "sign in"
]

noise_records = []

for _, row in extracted_documents.iterrows():

    text_lower = (
        row["cleaned_text"]
        .lower()
    )

    found_patterns = [
        pattern
        for pattern in NOISE_PATTERNS
        if pattern in text_lower
    ]

    noise_records.append({
        "source_id":
            row["source_id"],

        "title":
            row["title"],

        "noise_pattern_count":
            len(found_patterns),

        "patterns":
            "; ".join(
                found_patterns
            )
    })


noise_audit = pd.DataFrame(
    noise_records
)

print("WEB/PAGE NOISE AUDIT")
print("=" * 60)

display(
    noise_audit
)

WEB/PAGE NOISE AUDIT
============================================================

,source_id,title,noise_pattern_count,patterns
0,SRC_001,"IFRC International First Aid, Resuscitation an...",1,accessibility
1,SRC_005,During a Flood,1,privacy policy
2,SRC_006,Lightning Safety,1,privacy policy
3,SRC_007,During a High Wind Event,1,privacy policy
4,SRC_008,Before a High Wind Event,1,privacy policy
5,SRC_009,Outdoor Emergency Plan,3,privacy policy; accessibility; menu
6,SRC_010,Ten Essentials,3,privacy policy; accessibility; menu
7,SRC_014,Hypothermia,0,
8,SRC_015,Heat exhaustion and heatstroke,0,
9,SRC_016,Cuts and grazes,0,
10,SRC_017,Emergency Disinfection of Drinking Water,0,

In [17]:
CHUNK_SIZE_WORDS = 180
CHUNK_OVERLAP_WORDS = 40


def chunk_text(
    text,
    chunk_size=CHUNK_SIZE_WORDS,
    overlap=CHUNK_OVERLAP_WORDS
):

    words = text.split()

    if not words:
        return []

    chunks = []

    start = 0

    while start < len(words):

        end = min(
            start + chunk_size,
            len(words)
        )

        chunk = " ".join(
            words[start:end]
        ).strip()

        if chunk:
            chunks.append(
                chunk
            )

        if end >= len(words):
            break

        start = (
            end - overlap
        )

    return chunks

In [18]:
catalog_lookup = (
    offline_catalog
    .set_index("source_id")
)

chunk_records = []

global_chunk_number = 1

for _, document in extracted_documents.iterrows():

    source_id = document[
        "source_id"
    ]

    source_metadata = (
        catalog_lookup.loc[
            source_id
        ]
    )

    chunks = chunk_text(
        document[
            "cleaned_text"
        ]
    )

    for local_index, chunk in enumerate(
        chunks,
        start=1
    ):

        chunk_records.append({
            "chunk_id":
                f"CHK_{global_chunk_number:05d}",

            "source_id":
                source_id,

            "source_chunk_index":
                local_index,

            "title":
                source_metadata[
                    "title"
                ],

            "organization":
                source_metadata[
                    "organization"
                ],

            "categories":
                source_metadata[
                    "categories"
                ],

            "source_url":
                source_metadata[
                    "source_url"
                ],

            "word_count":
                len(
                    chunk.split()
                ),

            "content":
                chunk
        })

        global_chunk_number += 1


knowledge_chunks = pd.DataFrame(
    chunk_records
)

print("KNOWLEDGE CHUNKING")
print("=" * 60)

print(
    "Total chunks:",
    len(knowledge_chunks)
)

print(
    "Duplicate chunk IDs:",
    knowledge_chunks[
        "chunk_id"
    ].duplicated().sum()
)

print(
    "Empty chunks:",
    (
        knowledge_chunks[
            "content"
        ].str.strip() == ""
    ).sum()
)

print(
    "Mean words per chunk:",
    round(
        knowledge_chunks[
            "word_count"
        ].mean(),
        2
    )
)

print(
    "Maximum words:",
    knowledge_chunks[
        "word_count"
    ].max()
)

print(
    "Minimum words:",
    knowledge_chunks[
        "word_count"
    ].min()
)

KNOWLEDGE CHUNKING
============================================================
Total chunks: 1676
Duplicate chunk IDs: 0
Empty chunks: 0
Mean words per chunk: 179.63
Maximum words: 180
Minimum words: 63

In [19]:
chunk_distribution = (
    knowledge_chunks
    .groupby(
        [
            "source_id",
            "title"
        ]
    )
    .size()
    .reset_index(
        name="chunk_count"
    )
    .sort_values(
        "chunk_count",
        ascending=False
    )
)

chunk_distribution[
    "corpus_percent"
] = (
    chunk_distribution[
        "chunk_count"
    ]
    /
    len(
        knowledge_chunks
    )
    * 100
)

print("CHUNK DISTRIBUTION")
print("=" * 60)

display(
    chunk_distribution
)

CHUNK DISTRIBUTION
============================================================

,source_id,title,chunk_count,corpus_percent
0,SRC_001,"IFRC International First Aid, Resuscitation an...",1622,96.778043
5,SRC_009,Outdoor Emergency Plan,13,0.775656
6,SRC_010,Ten Essentials,8,0.477327
10,SRC_017,Emergency Disinfection of Drinking Water,8,0.477327
9,SRC_016,Cuts and grazes,6,0.357995
8,SRC_015,Heat exhaustion and heatstroke,5,0.298329
3,SRC_007,During a High Wind Event,4,0.238663
1,SRC_005,During a Flood,3,0.178998
7,SRC_014,Hypothermia,3,0.178998
2,SRC_006,Lightning Safety,2,0.119332
4,SRC_008,Before a High Wind Event,2,0.119332

In [20]:
required_chunk_columns = [
    "chunk_id",
    "source_id",
    "source_chunk_index",
    "title",
    "organization",
    "categories",
    "source_url",
    "word_count",
    "content"
]

missing_chunk_columns = [
    column
    for column in required_chunk_columns
    if column not in knowledge_chunks.columns
]

unknown_source_ids = (
    set(
        knowledge_chunks[
            "source_id"
        ]
    )
    -
    set(
        offline_catalog[
            "source_id"
        ]
    )
)

missing_provenance = (
    knowledge_chunks[
        [
            "source_id",
            "title",
            "organization",
            "source_url"
        ]
    ]
    .isna()
    .sum()
    .sum()
)

print("CHUNK VALIDATION")
print("=" * 60)

print(
    "Missing required columns:",
    missing_chunk_columns
)

print(
    "Unknown source IDs:",
    unknown_source_ids
)

print(
    "Missing provenance values:",
    missing_provenance
)

print(
    "Duplicate chunk IDs:",
    knowledge_chunks[
        "chunk_id"
    ].duplicated().sum()
)

print(
    "Valid:",
    (
        len(missing_chunk_columns) == 0
        and len(unknown_source_ids) == 0
        and missing_provenance == 0
        and knowledge_chunks[
            "chunk_id"
        ].duplicated().sum() == 0
    )
)

CHUNK VALIDATION
============================================================
Missing required columns: []
Unknown source IDs: set()
Missing provenance values: 0
Duplicate chunk IDs: 0
Valid: True

In [21]:
preview_sources = [
    "SRC_001",
    "SRC_005",
    "SRC_014",
    "SRC_017"
]

for source_id in preview_sources:

    sample = (
        knowledge_chunks[
            knowledge_chunks[
                "source_id"
            ] == source_id
        ]
        .head(2)
    )

    print("\n")
    print("=" * 80)
    print(source_id)

    for _, row in sample.iterrows():

        print(
            "\n",
            row["chunk_id"],
            "|",
            row["organization"]
        )

        print("-" * 80)

        print(
            row["content"]
        )

================================================================================
SRC_001

 CHK_00001 | IFRC
--------------------------------------------------------------------------------
INTERNATIONAL FIRST AID, RESUSCITATION AND EDUCATION GUIDELINES 2025 Contents TOPIC INDEX 4 INTRODUCTION 11 CONTEXTUALIZING FIRST AID AND FIRST AID EDUCATION 27 FIRST AID EDUCATION 71 FIRST AID 111 GENERAL APPROACH 113 RESUSCITATION 151 BREATHING PROBLEMS 231 TRAUMA 255 MEDICAL CONDITIONS 357 ENVIRONMENTAL 445 MENTAL DISTRESS 485 GLOSSARY AND REFERENCES 523 Audience: First aid programme designers, programme managers, education and scienti ﬁc committees, trainers Red Cross Red Crescent Networks Coordinated by IFRC Global First Aid Reference Centre © International Federation of Red Cross and Red Crescent Societies, Geneva, 2025 Copies of all or part of this study may be made for non-commercial use, providing the source is acknowledged. The IFRC would appreciate receiving details of its use. Requests for commercial reproduction should be directed to the IFRC at secretariat@ifrc.org. The opinions and recommendations expressed in this study do not necessarily represent the ofﬁcial policy of the IFRC or of individual National Red Cross or Red Crescent Societies. All photos used in this study are copyright of the IFRC unless otherwise indicated. Chemin des Crêts 17, Petit-Saconnex, 1209 Geneva, Switzerland Postal

 CHK_00002 | IFRC
--------------------------------------------------------------------------------
represent the ofﬁcial policy of the IFRC or of individual National Red Cross or Red Crescent Societies. All photos used in this study are copyright of the IFRC unless otherwise indicated. Chemin des Crêts 17, Petit-Saconnex, 1209 Geneva, Switzerland Postal address: P.O. Box 303, 1211 Geneva 19, Switzerland T +41 (0)22 730 42 22 | secretariat@ifrc.org | ifrc.org International ﬁrst aid, resuscitation and education guidelines 2025 globalﬁrstaidcentre.org 2 | International ﬁrst aid, resuscitation and education guidelines 2025 ⚙ Foreword As we share the 2025 edition of the IFRC International First Aid, Resuscitation and Education Guidelines, I am struck by both the enduring relevance of ﬁrst aid and the remarkable progress made across our Red Cross and Red Crescent network to ensure that life-saving knowledge is placed in the hands of millions. Over the past ﬁve years, the world has continued to face profound challenges: public health emergencies, natural disasters driven by climate change, con ﬂict and displacement, and rising mental health needs. In every crisis, one constant remains - people helping people by placing humanity at the centre of our


================================================================================
SRC_005

 CHK_01623 | NOAA National Weather Service (NWS)
--------------------------------------------------------------------------------
HOME FORECAST Local Graphical Aviation Marine Rivers and Lakes Hurricanes Severe Weather Fire Weather Sunrise/Sunset Long Range Forecasts Climate Prediction Space Weather PAST WEATHER Past Weather Astronomical Data Certified Weather Data SAFETY INFORMATION Wireless Emergency Alerts Weather-Ready Nation Brochures Cooperative Observers Daily Briefing Damage/Fatality/Injury Statistics Forecast Models GIS Data Portal NOAA Weather Radio Publications SKYWARN Storm Spotters StormReady TsunamiReady Service Change Notices EDUCATION NEWS SEARCH ABOUT About NWS Organization For NWS Employees National Centers Careers Contact Us Glossary Social Media NWS Transformation Safety National Program During a Flood Weather.gov > Safety > During a Flood Flooding Resources During a flood, water levels and the rate the water is flowing can quickly change. Remain aware and monitor local radio and television outlets. Avoid flood waters at all costs and evacuate immediately when water starts to rise. Don't wait until it's too late! Stay Informed: Listen to radio and television, including NOAA Weather Radio if possible, check the Internet and social media for information and updates. Get to Higher Ground: If you live in a flood prone area or are camping in

 CHK_01624 | NOAA National Weather Service (NWS)
--------------------------------------------------------------------------------
late! Stay Informed: Listen to radio and television, including NOAA Weather Radio if possible, check the Internet and social media for information and updates. Get to Higher Ground: If you live in a flood prone area or are camping in a low lying area, get to higher ground immediately. Obey Evacuation Orders: If told to evacuate, do so immediately. Lock your home when you leave. If you have time, disconnect utilities and appliances. Practice Electrical Safety: Don't go into a basement, or any room, if water covers the electrical outlets or if cords are submerged. If you see sparks or hear buzzing, crackling, snapping or popping noises--get out! Stay out of water that may have electricity in it! Avoid Flood Waters: Don't walk through flood waters. It only takes 6 inches of moving water to knock you off your feet. If you are trapped by moving water, move to the highest possible point and call 911 if possible. Do NOT drive into flooded roadways or around a barricade; Turn Around, Don't Drown! Water may be deeper than it appears and


================================================================================
SRC_014

 CHK_01655 | NHS (England)
--------------------------------------------------------------------------------
Hypothermia Hypothermia is a dangerous drop in body temperature below 35C (normal body temperature is around 37C). It's a medical emergency that needs to be treated in hospital. Symptoms of hypothermia Symptoms of hypothermia include: shivering pale, cold and dry skin – skin and lips may turn blue or grey (on black or brown skin this may be easier to see on the palms of the hands or the soles of the feet) slurred speech slow breathing tiredness or confusion A baby with hypothermia may be: cold to touch floppy unusually quiet and sleepy and may refuse to feed Immediate action required: Go to A&E or call 999 if: you think you or your child have hypothermia Find your nearest A&E Information: Do not drive to A&E. Ask someone to drive you or call 999 and ask for an ambulance. Bring any medicines you take with you. What to do while you're waiting for help for hypothermia If you think someone has hypothermia, there are things you can do while waiting for medical help. Do move the person indoors or

 CHK_01656 | NHS (England)
--------------------------------------------------------------------------------
Bring any medicines you take with you. What to do while you're waiting for help for hypothermia If you think someone has hypothermia, there are things you can do while waiting for medical help. Do move the person indoors or somewhere sheltered as quickly as possible remove any wet clothing, wrap them in a blanket, sleeping bag or dry towel, making sure their head is covered give them a warm non-alcoholic drink and some sugary food like chocolate if they're fully awake keep them awake by talking to them until help arrives make sure you or someone else stays with them There are things you should not do because they will not help and could make things worse. Don’t do not use a hot bath, hot water bottle or heat lamp to warm them up do not rub their arms, legs, feet or hands do not give them alcohol to drink Treatment in hospital for hypothermia If you have hypothermia, you’ll usually be treated in hospital. Your heart rate will be monitored and you may be given oxygen to help


================================================================================
SRC_017

 CHK_01669 | US Environmental Protection Agency (EPA)
--------------------------------------------------------------------------------
Breadcrumb Home Ground Water and Drinking Water Emergency Disinfection of Drinking Water Información relacionada disponible en español In an emergency situation where regular water service has been interrupted – like a hurricane, flood, or water pipe breakage – local authorities may recommend using only bottled water, boiled water, or disinfected water until regular water service is restored. The instructions below show you how to boil and disinfect water to kill most disease-causing microorganisms that may be present in the water. However, boiling or disinfection will not destroy other contaminants, such as heavy metals, salts, and most other chemicals. Print Emergency Disinfection of Drinking Water document. ONLY USE WATER THAT HAS BEEN PROPERLY DISINFECTED FOR DRINKING, COOKING, MAKING ANY PREPARED DRINK, WASHING DISHES AND FOR BRUSHING TEETH. Use bottled water or water you have properly prepared and stored as an emergency water supply. Boil water , if you do not have bottled water. Boiling is sufficient to kill pathogenic bacteria, viruses and protozoa (WHO, 2015). If water is cloudy, let it settle and filter it through a clean cloth, paperboiling water

 CHK_01670 | US Environmental Protection Agency (EPA)
--------------------------------------------------------------------------------
water supply. Boil water , if you do not have bottled water. Boiling is sufficient to kill pathogenic bacteria, viruses and protozoa (WHO, 2015). If water is cloudy, let it settle and filter it through a clean cloth, paperboiling water towel, or coffee filter. Bring water to a rolling boil for at least one minute. At altitudes above 5,000 feet (1,000 meters), boil water for three minutes. Let water cool naturally and store it in clean containers with covers. To improve the flat taste of boiled water, add one pinch of salt to each quart or liter of water, or pour the water from one clean container to another several times. Disinfect water using household bleach , if you can’t boil water. Only use regular, unscented chlorine bleach products that are suitable for disinfection and sanitization as indicated on the label. The label may say that the active ingredient contains 6 or 8.25% of sodium hypochlorite. Do not use scented, color safe, or bleaches with added cleaners. If water is cloudy, let it settle and filter it through a clean

## Offline SQLite Retrieval Layer

In [22]:
CHUNKS_FILE = (
    PROCESSED_DIR
    / "knowledge_chunks.csv"
)

knowledge_chunks.to_csv(
    CHUNKS_FILE,
    index=False
)

print("PROCESSED CORPUS")
print("=" * 60)

print(
    "Saved:",
    CHUNKS_FILE.exists()
)

print(
    "Rows:",
    len(knowledge_chunks)
)

print(
    "Path:",
    CHUNKS_FILE
)

PROCESSED CORPUS
============================================================
Saved: True
Rows: 1676
Path: /Users/mirshad/Desktop/Decentralized-Hiking-AI/research/rag/processed/knowledge_chunks.csv

In [23]:
DATABASE_FILE = (
    DATABASE_DIR
    / "offline_hiking_knowledge.db"
)

if DATABASE_FILE.exists():
    DATABASE_FILE.unlink()

connection = sqlite3.connect(
    DATABASE_FILE
)

cursor = connection.cursor()

cursor.execute("""
CREATE TABLE documents (
    source_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    organization TEXT NOT NULL,
    categories TEXT NOT NULL,
    source_url TEXT NOT NULL,
    file_type TEXT,
    local_path TEXT
)
""")

cursor.execute("""
CREATE TABLE knowledge_chunks (
    chunk_id TEXT PRIMARY KEY,
    source_id TEXT NOT NULL,
    source_chunk_index INTEGER NOT NULL,
    categories TEXT NOT NULL,
    word_count INTEGER NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY (source_id)
        REFERENCES documents(source_id)
)
""")

connection.commit()

print("SQLITE DATABASE")
print("=" * 60)

print(
    "Created:",
    DATABASE_FILE.exists()
)

print(
    "Path:",
    DATABASE_FILE
)

SQLITE DATABASE
============================================================
Created: True
Path: /Users/mirshad/Desktop/Decentralized-Hiking-AI/research/rag/database/offline_hiking_knowledge.db

In [24]:
document_rows = []

for _, row in offline_catalog.iterrows():

    document_rows.append((
        str(row["source_id"]),
        str(row["title"]),
        str(row["organization"]),
        str(row["categories"]),
        str(row["source_url"]),
        str(row["file_type"]),
        str(row["local_path"])
    ))

cursor.executemany("""
INSERT INTO documents (
    source_id,
    title,
    organization,
    categories,
    source_url,
    file_type,
    local_path
)
VALUES (?, ?, ?, ?, ?, ?, ?)
""", document_rows)

connection.commit()

document_count = cursor.execute(
    "SELECT COUNT(*) FROM documents"
).fetchone()[0]

print("DOCUMENT INSERTION")
print("=" * 60)

print(
    "Documents inserted:",
    document_count
)

DOCUMENT INSERTION
============================================================
Documents inserted: 11

In [25]:
chunk_rows = []

for _, row in knowledge_chunks.iterrows():

    chunk_rows.append((
        str(row["chunk_id"]),
        str(row["source_id"]),
        int(row["source_chunk_index"]),
        str(row["categories"]),
        int(row["word_count"]),
        str(row["content"])
    ))

cursor.executemany("""
INSERT INTO knowledge_chunks (
    chunk_id,
    source_id,
    source_chunk_index,
    categories,
    word_count,
    content
)
VALUES (?, ?, ?, ?, ?, ?)
""", chunk_rows)

connection.commit()

chunk_count = cursor.execute(
    "SELECT COUNT(*) FROM knowledge_chunks"
).fetchone()[0]

print("CHUNK INSERTION")
print("=" * 60)

print(
    "Chunks inserted:",
    chunk_count
)

CHUNK INSERTION
============================================================
Chunks inserted: 1676

In [26]:
cursor.execute("""
CREATE VIRTUAL TABLE knowledge_chunks_fts
USING fts5(
    chunk_id UNINDEXED,
    source_id UNINDEXED,
    categories UNINDEXED,
    content
)
""")

cursor.execute("""
INSERT INTO knowledge_chunks_fts (
    chunk_id,
    source_id,
    categories,
    content
)
SELECT
    chunk_id,
    source_id,
    categories,
    content
FROM knowledge_chunks
""")

connection.commit()

fts_count = cursor.execute(
    "SELECT COUNT(*) FROM knowledge_chunks_fts"
).fetchone()[0]

print("FTS5 INDEX")
print("=" * 60)

print(
    "Indexed chunks:",
    fts_count
)

FTS5 INDEX
============================================================
Indexed chunks: 1676

In [27]:
database_validation = {
    "documents":
        cursor.execute(
            "SELECT COUNT(*) FROM documents"
        ).fetchone()[0],

    "knowledge_chunks":
        cursor.execute(
            "SELECT COUNT(*) FROM knowledge_chunks"
        ).fetchone()[0],

    "fts_chunks":
        cursor.execute(
            "SELECT COUNT(*) FROM knowledge_chunks_fts"
        ).fetchone()[0]
}

print("DATABASE VALIDATION")
print("=" * 60)

for key, value in database_validation.items():
    print(
        f"{key}: {value}"
    )

print()

database_valid = (
    database_validation[
        "documents"
    ] == 11

    and

    database_validation[
        "knowledge_chunks"
    ] == 1676

    and

    database_validation[
        "fts_chunks"
    ] == 1676
)

print(
    "Database valid:",
    database_valid
)

print(
    "Database size:",
    f"{DATABASE_FILE.stat().st_size / (1024 ** 2):.2f} MB"
)

DATABASE VALIDATION
============================================================
documents: 11
knowledge_chunks: 1676
fts_chunks: 1676

Database valid: True
Database size: 6.27 MB

In [28]:
def prepare_fts_query(question):

    terms = re.findall(
        r"[A-Za-z0-9]+",
        question.lower()
    )

    stop_words = {
        "a", "an", "the", "and", "or",
        "is", "are", "was", "were",
        "i", "me", "my", "we", "our",
        "to", "of", "for", "in", "on",
        "at", "with", "if", "do", "does",
        "what", "should", "how", "can"
    }

    terms = [
        term
        for term in terms
        if term not in stop_words
        and len(term) > 1
    ]

    if not terms:
        return None

    return " OR ".join(
        f'"{term}"'
        for term in terms
    )


def retrieve_chunks(
    question,
    category=None,
    limit=5
):

    fts_query = prepare_fts_query(
        question
    )

    if not fts_query:
        return pd.DataFrame()

    parameters = [
        fts_query
    ]

    category_condition = ""

    if category is not None:

        category_condition = """
        AND kc.categories LIKE ?
        """

        parameters.append(
            f"%{category}%"
        )

    parameters.append(
        max(
            limit * 5,
            20
        )
    )

    sql = f"""
    SELECT
        kc.chunk_id,
        kc.source_id,
        d.title,
        d.organization,
        kc.categories,
        d.source_url,
        kc.content,
        bm25(knowledge_chunks_fts) AS rank
    FROM knowledge_chunks_fts
    JOIN knowledge_chunks kc
        ON kc.chunk_id =
           knowledge_chunks_fts.chunk_id
    JOIN documents d
        ON d.source_id = kc.source_id
    WHERE knowledge_chunks_fts
          MATCH ?
    {category_condition}
    ORDER BY rank
    LIMIT ?
    """

    results = pd.read_sql_query(
        sql,
        connection,
        params=parameters
    )

    if results.empty:
        return results

    # Source diversification:
    # prevent one large source from occupying
    # every returned position.
    selected_rows = []
    source_counts = {}

    for _, row in results.iterrows():

        source_id = row[
            "source_id"
        ]

        count = source_counts.get(
            source_id,
            0
        )

        if count >= 2:
            continue

        selected_rows.append(
            row
        )

        source_counts[
            source_id
        ] = count + 1

        if len(
            selected_rows
        ) >= limit:
            break

    return pd.DataFrame(
        selected_rows
    ).reset_index(
        drop=True
    )

In [29]:
test_question = (
    "What should I do if a hiker "
    "shows signs of hypothermia?"
)

results = retrieve_chunks(
    question=test_question,
    category="hypothermia",
    limit=5
)

print("OFFLINE RETRIEVAL TEST")
print("=" * 60)

print(
    "Question:",
    test_question
)

print(
    "Results:",
    len(results)
)

display(
    results[
        [
            "chunk_id",
            "source_id",
            "organization",
            "rank"
        ]
    ]
)

for _, row in results.iterrows():

    print("\n")
    print(
        row["chunk_id"],
        "|",
        row["organization"]
    )

    print("-" * 70)

    print(
        row["content"][:1000]
    )

OFFLINE RETRIEVAL TEST
============================================================
Question: What should I do if a hiker shows signs of hypothermia?
Results: 4

    chunk_id source_id   organization      rank
0  CHK_01246   SRC_001           IFRC -8.259663
1  CHK_01247   SRC_001           IFRC -7.089062
2  CHK_01655   SRC_014  NHS (England) -7.029797
3  CHK_01657   SRC_014  NHS (England) -6.920280

CHK_01246 | IFRC
----------------------------------------------------------------------
muscles further. ● Do not apply warm stones directly to the skin as this may burn the person. ● If the person becomes unresponsive, open their airway and check for breathing. See Unresponsiveness. ● In a limited-resource setting, create a heat source (such as a campﬁre) to warm the person and build a shelter to protect them from the cold. Ensure there is a layer, such as a blanket, between the person and the ground. Access help For all cases of hypothermia, the ﬁrst aid provider should access emergency medical care immediately. Recovery Most healthy people with mild to moderate hypothermia will recover fully. However, if signs and symptoms continue or additional ones appear, seek medical care. Education considerations Context considerations ● Learners in or visiting cold climates may bene ﬁt from learning how to prevent hypothermia and frostbite (including winter conditions in any setting, and speci ﬁc settings such as the mountains). ● CPR in a hypothermic person will be prolonged. ●


CHK_01247 | IFRC
----------------------------------------------------------------------
winter conditions in any setting, and speci ﬁc settings such as the mountains). ● CPR in a hypothermic person will be prolonged. ● Include information on accessing help in rural or remote environments. ● Programme designers should consider that hypothermia can also occur in the home (e.g. older people who are unable or choose not to turn on the heat in cold weather, or people who slip on icy steps and cannot help themselves up). ● Hypothermia can even occur in warm temperatures if a person is wet and inactive. ● In some contexts, learners may bene ﬁt from learning about reducing the risk of experiencing an avalanche, including familiarization with local avalanche warning signs and safe behaviours to follow (e.g. avoid closed ski slopes). Facilitation tips ● Make learning contextual; facilitating a session outside in cold conditions can reinforce the reality of what a learner may experience in this type of emergency. ● Plan to include environmental conditions at the end of a session as


CHK_01655 | NHS (England)
----------------------------------------------------------------------
Hypothermia Hypothermia is a dangerous drop in body temperature below 35C (normal body temperature is around 37C). It's a medical emergency that needs to be treated in hospital. Symptoms of hypothermia Symptoms of hypothermia include: shivering pale, cold and dry skin – skin and lips may turn blue or grey (on black or brown skin this may be easier to see on the palms of the hands or the soles of the feet) slurred speech slow breathing tiredness or confusion A baby with hypothermia may be: cold to touch floppy unusually quiet and sleepy and may refuse to feed Immediate action required: Go to A&E or call 999 if: you think you or your child have hypothermia Find your nearest A&E Information: Do not drive to A&E. Ask someone to drive you or call 999 and ask for an ambulance. Bring any medicines you take with you. What to do while you're waiting for help for hypothermia If you think someone has hypothermia, there are things you can do while waiting for medical help. Do move the person indoo


CHK_01657 | NHS (England)
----------------------------------------------------------------------
legs, feet or hands do not give them alcohol to drink Treatment in hospital for hypothermia If you have hypothermia, you’ll usually be treated in hospital. Your heart rate will be monitored and you may be given oxygen to help you breathe. You may also be given warm fluids straight into a vein to help your body warm up. Treatment in intensive care may be needed if you have severe hypothermia. Causes of hypothermia Hypothermia happens when you get too cold and your body temperature drops below 35C. You can get hypothermia if you: do not wear enough clothes in cold weather stay out in the cold too long fall into cold water have wet clothes and get cold live in a cold house – older people living alone are particularly at risk Page last reviewed: 09 June 2023 Next review due: 09 June 2026